name: chatgpt_drawer_view
description: "ChatGPT Drawer View"
#publish_to: 'none'
repository: https://github.com/juneview-songdo/chatgpt_drawer_view

version: 1.0.3

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  hive:
  isar_flutter_libs:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  path_provider:
  styled_widget:

dev_dependencies:
  bot_toast_module:
  config_theme:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  hive_module:
  june_view:  #@add
  june_view_more:  #@add
  screenutil_module:
  theme_mode_changer: #@add

flutter:
  assets:
    - assets/view/chatgpt_drawer_view/
  uses-material-design: true